site_name: Virtual Gamepad Emulation Framework
site_url: https://vigem.org
repo_url: https://github.com/ViGEm/ViGEm.github.io
site_description: Projects devoted to USB input device emulation and game peripherals reverse engineering
copyright: |
  Copyright &copy; 2020 - 2021 <a href="https://github.com/nefarius" target="_blank" rel="noopener">Benjamin HÃ¶glinger-Stelzer</a>

theme:
  name: material
  favicon: images/favicon.png
  features:
    - navigation.expand
  palette:
    primary: teal
  features:
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ViGEm
    - icon: fontawesome/brands/discord
      link: https://discord.vigem.org
extra_css:
  - stylesheets/glightbox.css
extra_javascript:
  - javascripts/glightbox.js
  - javascripts/main.js

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.tabbed:
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true